################################################################
# Build notes
################################################################

# Requires a recent gcc, e.g.:
#   . /opt/rh/devtoolset-2/enable
# This is also needed for icc as it uses gcc headers.


################################################################
# Configuration section
################################################################

# 1. Use ROOT or not
# Comment out or set to anything but "yes" to disable root
# WITH_ROOT := yes

# 2. Use gcc or icc
# Uncomment to use icc. For mic icc is always used.
# CXX := icc

# 3. Optimization
# -O3 implies vectorization and simd (but not AVX)
OPT := -O3

# 4. Vectorization settings
VEC_GCC  := -mavx # -fopt-info-vec
VEC_REP  := 1
VEC_ICC  := -mavx -vec-report=${VEC_REP}
VEC_MIC  := -mmic -vec-report=${VEC_REP}

# 5. Matriplex, intrinsics
# Comment-out for no intrinsics
# USE_INTRINSICS := -DMPLEX_USE_INTRINSICS

# 6. MIC stuff is built when icc is the chosen compiler


################################################################
# Derived settings
################################################################

CPPFLAGS := -I. -MMD ${USE_INTRINSICS}
CXXFLAGS := ${OPT} -std=c++11
LDFLAGS  :=

ifeq ($(CXX),icc)
  CXXFLAGS += -openmp
  LDFLAGS  += -openmp
  VEC_HOST := ${VEC_ICC}
else
  CXXFLAGS += -fopenmp -Wall -Wno-unknown-pragmas
  LDFLAGS  += -fopenmp
  VEC_HOST := ${VEC_GCC}
endif

CPPFLAGS_NO_ROOT := ${CPPFLAGS} -DNO_ROOT
LDFLAGS_NO_ROOT  := ${LDFLAGS}

ifeq (${WITH_ROOT},yes)
  CPPFLAGS += $(shell root-config --cflags)
  LDFLAGS  += $(shell root-config --libs)
else
  CPPFLAGS += -DNO_ROOT
endif
