{

  TFile* f = TFile::Open("benchmark.root");

  TCanvas c1;
  TGraph* g_HOST_BH_VU = (TGraph*) f->Get("g_HOST_BH_VU");
  TGraph* g_HOST_CE_VU = (TGraph*) f->Get("g_HOST_CE_VU");
  TGraph* g_HOST_CEST_VU = (TGraph*) f->Get("g_HOST_CEST_VU");
  g_HOST_BH_VU->SetTitle("Vectorization benchmark on Host");
  g_HOST_BH_VU->GetXaxis()->SetTitle("Vector Unit Utilization");
  g_HOST_BH_VU->GetYaxis()->SetTitle("Time for 10 events x 20k tracks [s]");
  g_HOST_BH_VU->GetXaxis()->SetRangeUser(1,8);
  g_HOST_BH_VU->GetYaxis()->SetRangeUser(0,10);
  g_HOST_BH_VU->SetLineWidth(2);
  g_HOST_CE_VU->SetLineWidth(2);
  g_HOST_CEST_VU->SetLineWidth(2);
  g_HOST_BH_VU->SetLineColor(kBlue);
  g_HOST_CE_VU->SetLineColor(kRed);
  g_HOST_CEST_VU->SetLineColor(kMagenta);
  g_HOST_BH_VU->SetMarkerStyle(kFullCircle);
  g_HOST_CE_VU->SetMarkerStyle(kFullCircle);
  g_HOST_CEST_VU->SetMarkerStyle(kFullCircle);
  g_HOST_BH_VU->SetMarkerColor(kBlue);
  g_HOST_CE_VU->SetMarkerColor(kRed);
  g_HOST_CEST_VU->SetMarkerColor(kMagenta);
  g_HOST_BH_VU->Draw("ALP");
  g_HOST_CE_VU->Draw("LP");
  g_HOST_CEST_VU->Draw("LP");
  TLegend* leg_VU = new TLegend(0.60,0.60,0.85,0.85);
  leg_VU->SetBorderSize(0);
  leg_VU->AddEntry(g_HOST_BH_VU,"BestHit","LP");
  leg_VU->AddEntry(g_HOST_CE_VU,"CloneEngine","LP");
  leg_VU->AddEntry(g_HOST_CEST_VU,"CESingleThread","LP");
  leg_VU->Draw();
  c1.SetGridy();
  c1.Update();
  c1.SaveAs("host_vu_time.png");

  TCanvas c2;
  TGraph* g_HOST_BH_VU_speedup = (TGraph*) f->Get("g_HOST_BH_VU_speedup");
  TGraph* g_HOST_CE_VU_speedup = (TGraph*) f->Get("g_HOST_CE_VU_speedup");
  TGraph* g_HOST_CEST_VU_speedup = (TGraph*) f->Get("g_HOST_CEST_VU_speedup");
  g_HOST_BH_VU_speedup->SetTitle("Vectorization speedup on Host");
  g_HOST_BH_VU_speedup->GetXaxis()->SetTitle("Vector Unit Utilization");
  g_HOST_BH_VU_speedup->GetYaxis()->SetTitle("Speedup");
  g_HOST_BH_VU_speedup->GetXaxis()->SetRangeUser(1,8);
  g_HOST_BH_VU_speedup->GetYaxis()->SetRangeUser(1,8);
  g_HOST_BH_VU_speedup->SetLineWidth(2);
  g_HOST_CE_VU_speedup->SetLineWidth(2);
  g_HOST_CEST_VU_speedup->SetLineWidth(2);
  g_HOST_BH_VU_speedup->SetLineColor(kBlue);
  g_HOST_CE_VU_speedup->SetLineColor(kRed);
  g_HOST_CEST_VU_speedup->SetLineColor(kMagenta);
  g_HOST_BH_VU_speedup->SetMarkerStyle(kFullCircle);
  g_HOST_CE_VU_speedup->SetMarkerStyle(kFullCircle);
  g_HOST_CEST_VU_speedup->SetMarkerStyle(kFullCircle);
  g_HOST_BH_VU_speedup->SetMarkerColor(kBlue);
  g_HOST_CE_VU_speedup->SetMarkerColor(kRed);
  g_HOST_CEST_VU_speedup->SetMarkerColor(kMagenta);
  g_HOST_BH_VU_speedup->Draw("ALP");
  g_HOST_CE_VU_speedup->Draw("LP");
  g_HOST_CEST_VU_speedup->Draw("LP");
  TLegend* leg_VU_speedup = new TLegend(0.20,0.60,0.45,0.85);
  leg_VU_speedup->SetBorderSize(0);
  leg_VU_speedup->AddEntry(g_HOST_BH_VU_speedup,"BestHit","LP");
  leg_VU_speedup->AddEntry(g_HOST_CE_VU_speedup,"CloneEngine","LP");
  leg_VU_speedup->AddEntry(g_HOST_CEST_VU_speedup,"CESingleThread","LP");
  leg_VU_speedup->Draw();
  c2.SetGridy();
  c2.Update();
  c2.SaveAs("host_vu_speedup.png");

  TCanvas c3;
  TGraph* g_HOST_BH_TH = (TGraph*) f->Get("g_HOST_BH_TH");
  TGraph* g_HOST_CE_TH = (TGraph*) f->Get("g_HOST_CE_TH");
  TGraph* g_HOST_CEST_TH = (TGraph*) f->Get("g_HOST_CEST_TH");
  g_HOST_BH_TH->SetTitle("Parallelization benchmark on Host");
  g_HOST_BH_TH->GetXaxis()->SetTitle("Number of Threads");
  g_HOST_BH_TH->GetYaxis()->SetTitle("Time for 10 events x 20k tracks [s]");
  g_HOST_BH_TH->GetXaxis()->SetRangeUser(1,21);
  g_HOST_BH_TH->GetYaxis()->SetRangeUser(0,6);
  g_HOST_BH_TH->SetLineWidth(2);
  g_HOST_CE_TH->SetLineWidth(2);
  g_HOST_CEST_TH->SetLineWidth(2);
  g_HOST_BH_TH->SetLineColor(kBlue);
  g_HOST_CE_TH->SetLineColor(kRed);
  g_HOST_CEST_TH->SetLineColor(kMagenta);
  g_HOST_BH_TH->SetMarkerStyle(kFullCircle);
  g_HOST_CE_TH->SetMarkerStyle(kFullCircle);
  g_HOST_CEST_TH->SetMarkerStyle(kFullCircle);
  g_HOST_BH_TH->SetMarkerColor(kBlue);
  g_HOST_CE_TH->SetMarkerColor(kRed);
  g_HOST_CEST_TH->SetMarkerColor(kMagenta);
  g_HOST_BH_TH->Draw("ALP");
  g_HOST_CE_TH->Draw("LP");
  g_HOST_CEST_TH->Draw("LP");
  TLegend* leg_TH = new TLegend(0.60,0.60,0.85,0.85);
  leg_TH->SetBorderSize(0);
  leg_TH->AddEntry(g_HOST_BH_TH,"BestHit","LP");
  leg_TH->AddEntry(g_HOST_CE_TH,"CloneEngine","LP");
  leg_TH->AddEntry(g_HOST_CEST_TH,"CESingleThread","LP");
  leg_TH->Draw();
  c3.SetGridy();
  c3.Update();
  c3.SaveAs("host_th_time.png");

  TCanvas c4;
  TGraph* g_HOST_BH_TH_speedup = (TGraph*) f->Get("g_HOST_BH_TH_speedup");
  TGraph* g_HOST_CE_TH_speedup = (TGraph*) f->Get("g_HOST_CE_TH_speedup");
  TGraph* g_HOST_CEST_TH_speedup = (TGraph*) f->Get("g_HOST_CEST_TH_speedup");
  g_HOST_BH_TH_speedup->SetTitle("Parallelization speedup on Host");
  g_HOST_BH_TH_speedup->GetXaxis()->SetTitle("Number of Threads");
  g_HOST_BH_TH_speedup->GetYaxis()->SetTitle("Speedup");
  g_HOST_BH_TH_speedup->GetXaxis()->SetRangeUser(0,21);
  g_HOST_BH_TH_speedup->GetYaxis()->SetRangeUser(0,21);
  g_HOST_BH_TH_speedup->SetLineWidth(2);
  g_HOST_CE_TH_speedup->SetLineWidth(2);
  g_HOST_CEST_TH_speedup->SetLineWidth(2);
  g_HOST_BH_TH_speedup->SetLineColor(kBlue);
  g_HOST_CE_TH_speedup->SetLineColor(kRed);
  g_HOST_CEST_TH_speedup->SetLineColor(kMagenta);
  g_HOST_BH_TH_speedup->SetMarkerStyle(kFullCircle);
  g_HOST_CE_TH_speedup->SetMarkerStyle(kFullCircle);
  g_HOST_CEST_TH_speedup->SetMarkerStyle(kFullCircle);
  g_HOST_BH_TH_speedup->SetMarkerColor(kBlue);
  g_HOST_CE_TH_speedup->SetMarkerColor(kRed);
  g_HOST_CEST_TH_speedup->SetMarkerColor(kMagenta);
  g_HOST_BH_TH_speedup->Draw("ALP");
  g_HOST_CE_TH_speedup->Draw("LP");
  g_HOST_CEST_TH_speedup->Draw("LP");
  TLegend* leg_TH_speedup = new TLegend(0.20,0.60,0.45,0.85);
  leg_TH_speedup->SetBorderSize(0);
  leg_TH_speedup->AddEntry(g_HOST_BH_TH_speedup,"BestHit","LP");
  leg_TH_speedup->AddEntry(g_HOST_CE_TH_speedup,"CloneEngine","LP");
  leg_TH_speedup->AddEntry(g_HOST_CEST_TH_speedup,"CESingleThread","LP");
  leg_TH_speedup->Draw();
  c4.SetGridy();
  c4.Update();
  c4.SaveAs("host_th_speedup.png");

}
